### ISSUE TITLE
CSS für LegendCard und LegendGallery (feat/be-create-packs)

### ISSUE THREAD

**Issue by hunjoonrhee** [SWMozart/TradingCards#2]
- Card design (Rahmen, Farbe, Positionierung von Texten, ... usw. )
- Gallery design (Rahmen, Farbe, ...)

**Comment by SWMozart** [comment]
???

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: hunjoonrhee ***@***.***>
Gesendet: Thursday, October 6, 2022 9:20:28 AM
An: SWMozart/TradingCards ***@***.***>
Cc: SWMozart ***@***.***>; Assign ***@***.***>
Betreff: Re: [SWMozart/TradingCards] CSS für LegendCard und LegendGallery (feat/be-create-packs) (Issue #2)


Assigned #2<https://github.com/SWMozart/TradingCards/issues/2> to @SWMozart<https://github.com/SWMozart>.
